-- =========================================================
-- PMV 1 · platform_db · datos semilla (ficticios)
-- Proyecto A: S/ 120 000 y 600 beneficiarios -> S/ 200 por persona
-- Proyecto B: S/  90 000 y 300 beneficiarios -> S/ 300 por persona
-- Politica activa v1: ECONOMIC = 100 %, excelente S/ 200, inaceptable S/ 500
-- created_by_user_id = UUID de las cuentas semilla de auth_db (sin FK)
-- =========================================================
INSERT INTO criteria_versions (id, version_number, status, excellent_cost_pen, unacceptable_cost_pen, created_by_user_id, activated_at)
VALUES ('c0000000-0000-4000-a000-000000000001', 1, 'active', 200.00, 500.00,
        '10000000-0000-4000-a000-000000000001', now())
ON CONFLICT (version_number) DO NOTHING;

INSERT INTO criterion_weights (criteria_version_id, criterion_code, weight_percent)
VALUES ('c0000000-0000-4000-a000-000000000001', 'ECONOMIC', 100.00)
ON CONFLICT DO NOTHING;

INSERT INTO projects (id, code, created_by_user_id, status) VALUES
    ('a0000000-0000-4000-a000-00000000000a', 'PRY-A', '10000000-0000-4000-a000-000000000002', 'ready'),
    ('a0000000-0000-4000-a000-00000000000b', 'PRY-B', '10000000-0000-4000-a000-000000000002', 'ready')
ON CONFLICT (code) DO NOTHING;

INSERT INTO project_versions (id, project_id, version_number, title, description, location_description,
                              proposed_land_use, territorial_data_origin, estimated_budget_pen,
                              beneficiaries_count, created_by_user_id) VALUES
    ('b0000000-0000-4000-a000-00000000000a', 'a0000000-0000-4000-a000-00000000000a', 1,
     'Proyecto A - Mejoramiento de losa deportiva (prueba)', 'Dato ficticio para el PMV 1',
     'CASO SIMULADO - distrito de El Tambo', 'recreacion', 'simulated', 120000.00, 600,
     '10000000-0000-4000-a000-000000000002'),
    ('b0000000-0000-4000-a000-00000000000b', 'a0000000-0000-4000-a000-00000000000b', 1,
     'Proyecto B - Ampliacion de veredas (prueba)', 'Dato ficticio para el PMV 1',
     'CASO SIMULADO - distrito de El Tambo', 'infraestructura vial', 'simulated', 90000.00, 300,
     '10000000-0000-4000-a000-000000000002')
ON CONFLICT (project_id, version_number) DO NOTHING;

UPDATE project_versions
SET location_description = 'CASO SIMULADO - distrito de El Tambo',
    proposed_land_use = CASE
        WHEN project_id = 'a0000000-0000-4000-a000-00000000000a' THEN 'recreacion'
        ELSE 'infraestructura vial'
    END,
    territorial_data_origin = 'simulated'
WHERE project_id IN (
    'a0000000-0000-4000-a000-00000000000a',
    'a0000000-0000-4000-a000-00000000000b'
) AND (location_description IS NULL OR proposed_land_use IS NULL);

-- =========================================================
-- HU2.1 / RF03 / RF12 · Corpus normativo con texto legal real (fuentes publicas oficiales)
-- 24 fragmentos normativos para El Tambo, Huancayo
-- 6 por cada grupo normativo: Ley 27972, DL 1252, Ley 32069, PDU/PDM
-- PDUPDM-02 y PDUPDM-04 marcados con has_alert=TRUE (causales de alerta)
-- Fuentes: leyes.congreso.gob.pe, busquedas.elperuano.pe, spij.minjus.gob.pe
-- =========================================================
INSERT INTO normative_documents (id, document_name, short_code, version, topic, content, in_force, has_alert, data_origin) VALUES
    ('LEY27972-01', 'Ley N.° 27972 - Ley Orgánica de Municipalidades', 'LEY_27972', '2003-v1', 'Competencias municipales (Art. 73)',
     'Art. 73.- Materias de competencia municipal. Las funciones específicas municipales que se derivan de las competencias se ejercen con carácter exclusivo o compartido entre las municipalidades provinciales y distritales. El rol de las municipalidades provinciales comprende: a) Planificar integralmente el desarrollo local y el ordenamiento territorial, en el nivel provincial. b) Promover la coordinación estratégica de los planes integrales de desarrollo distrital. c) Emitir las normas técnicas generales en materia de organización del espacio físico y uso del suelo. Fuente: leyes.congreso.gob.pe/Documentos/Leyes/27972.pdf', TRUE, FALSE, 'public'),
    ('LEY27972-02', 'Ley N.° 27972 - Ley Orgánica de Municipalidades', 'LEY_27972', '2003-v1', 'Organización del espacio físico y uso del suelo (Art. 79)',
     'Art. 79.- Organización del espacio físico y uso del suelo. Funciones exclusivas de municipalidades provinciales: 1.1 Aprobar el Plan de Acondicionamiento Territorial que identifique áreas urbanas, de expansión urbana, de protección o seguridad por riesgos naturales, áreas agrícolas y de conservación ambiental. 1.2 Aprobar el Plan de Desarrollo Urbano, el Plan de Desarrollo Rural, el Esquema de Zonificación de áreas urbanas y demás planes específicos. Funciones exclusivas distritales: 3.3 Normar, regular y otorgar autorizaciones, derechos y licencias para habilitaciones urbanas, construcción, remodelación o demolición de inmuebles, y apertura de establecimientos conforme a la zonificación. Fuente: leyes.congreso.gob.pe/Documentos/Leyes/27972.pdf', TRUE, FALSE, 'public'),
    ('LEY27972-03', 'Ley N.° 27972 - Ley Orgánica de Municipalidades', 'LEY_27972', '2003-v1', 'Concejo municipal - funciones normativas y fiscalizadoras (Arts. 5 y 9)',
     'Art. 5.- El concejo municipal, provincial y distrital, está conformado por el alcalde y el número de regidores que establezca el JNE. El concejo municipal ejerce funciones normativas y fiscalizadoras. Art. 9.- Atribuciones del concejo municipal: 1) Aprobar los Planes de Desarrollo Municipal Concertados y el Presupuesto Participativo. 5) Aprobar el Plan de Desarrollo Urbano, el Esquema de Zonificación. 8) Aprobar, modificar o derogar las ordenanzas y dejar sin efecto los acuerdos. 22) Fiscalizar la gestión pública de la municipalidad. Fuente: leyes.congreso.gob.pe/Documentos/Leyes/27972.pdf', TRUE, FALSE, 'public'),
    ('LEY27972-04', 'Ley N.° 27972 - Ley Orgánica de Municipalidades', 'LEY_27972', '2003-v1', 'Alcaldía - funciones ejecutivas (Arts. 6 y 20)',
     'Art. 6.- La alcaldía es el órgano ejecutivo del gobierno local. El alcalde es el representante legal de la municipalidad y su máxima autoridad administrativa. Art. 20.- Son atribuciones del alcalde: 1) Defender y cautelar los derechos e intereses de la municipalidad y los vecinos. 3) Ejecutar los acuerdos del concejo municipal, bajo responsabilidad. 6) Dictar decretos y resoluciones de alcaldía, con sujeción a las leyes y ordenanzas. 7) Dirigir la ejecución de los planes de desarrollo municipal. 29) Administrar los recursos económicos y financieros, de acuerdo con la ley y el presupuesto aprobado. Fuente: leyes.congreso.gob.pe/Documentos/Leyes/27972.pdf', TRUE, FALSE, 'public'),
    ('LEY27972-05', 'Ley N.° 27972 - Ley Orgánica de Municipalidades', 'LEY_27972', '2003-v1', 'Servicios públicos locales (Arts. IV TP, 73.2 y 80)',
     'Art. IV TP.- Los gobiernos locales representan al vecindario, promueven la adecuada prestación de los servicios públicos locales y el desarrollo integral, sostenible y armónico de su circunscripción. Art. 73.2.- Servicios públicos locales: saneamiento ambiental, salubridad y salud; tránsito, circulación y transporte público; educación, cultura, deporte y recreación; seguridad ciudadana; abastecimiento y comercialización. Art. 80.- Municipalidades distritales: proveer limpieza pública, regular aseo e higiene en establecimientos comerciales, industriales y viviendas, instalar y mantener servicios higiénicos públicos. Fuente: leyes.congreso.gob.pe/Documentos/Leyes/27972.pdf', TRUE, FALSE, 'public'),
    ('LEY27972-06', 'Ley N.° 27972 - Ley Orgánica de Municipalidades', 'LEY_27972', '2003-v1', 'Planeamiento y presupuesto participativo (Arts. IX TP, 53 y 97)',
     'Art. IX TP.- El proceso de planeación local es integral, permanente y participativo, articulando a las municipalidades con sus vecinos. Art. 53.- Las municipalidades se rigen por presupuestos participativos anuales como instrumentos de administración y gestión, los cuales se formulan, aprueban y ejecutan conforme a la ley de la materia, y en concordancia con los planes de desarrollo concertados de su jurisdicción. El presupuesto municipal debe sustentarse en el equilibrio real de sus ingresos y egresos. Art. 97.- El Consejo de Coordinación Local Provincial procede a coordinar, concertar y proponer el Plan de Desarrollo Municipal Provincial Concertado. Fuente: leyes.congreso.gob.pe/Documentos/Leyes/27972.pdf', TRUE, FALSE, 'public'),

    ('DL1252-01', 'D. L. N.° 1252 - Invierte.pe (TUO D.S. 242-2018-EF)', 'DL_1252', '2018-TUO', 'Programación multianual de inversiones (Art. 4.1.a)',
     'Art. 4.1.a) Programación Multianual de Inversiones: Consiste en un proceso de coordinación y articulación interinstitucional e intergubernamental, de proyección trianual, como mínimo, tomando en cuenta los fondos públicos destinados a la inversión proyectados en el Marco Macroeconómico Multianual. Dicha programación debe vincular los objetivos nacionales, regionales y locales establecidos en el planeamiento estratégico con la priorización y asignación multianual de fondos públicos, y orientarse al cierre de brechas de infraestructura o de acceso a servicios públicos para la población. Fuente: busquedas.elperuano.pe - D.S. 242-2018-EF', TRUE, FALSE, 'public'),
    ('DL1252-02', 'D. L. N.° 1252 - Invierte.pe (TUO D.S. 242-2018-EF)', 'DL_1252', '2018-TUO', 'Formulación y evaluación de proyectos (Art. 4.1.b)',
     'Art. 4.1.b) Formulación y Evaluación: Comprende la formulación del proyecto, de aquellas propuestas de inversión necesarias para alcanzar las metas establecidas en la programación multianual, y la evaluación sobre la pertinencia de su ejecución, debiendo considerarse los recursos para la operación y mantenimiento del proyecto y las formas de financiamiento. La formulación se realiza a través de una ficha técnica y solo en el caso de proyectos de alta complejidad se requiere el nivel de estudio que sustente la concepción técnica y el dimensionamiento. Los proyectos deben encontrarse registrados en el Banco de Inversiones. Fuente: busquedas.elperuano.pe - D.S. 242-2018-EF', TRUE, FALSE, 'public'),
    ('DL1252-03', 'D. L. N.° 1252 - Invierte.pe (TUO D.S. 242-2018-EF)', 'DL_1252', '2018-TUO', 'Ejecución de inversiones (Art. 4.1.c y 4.3)',
     'Art. 4.1.c) Ejecución: Comprende la elaboración del expediente técnico o documento equivalente y la ejecución física y financiera respectiva. Art. 4.3.- Únicamente pueden asignarse fondos públicos e iniciarse la fase de Ejecución de aquellas inversiones que están registradas en el Banco de Inversiones y cuenten con la declaración de viabilidad, cuando corresponda. Fuente: busquedas.elperuano.pe - D.L. 1252', TRUE, FALSE, 'public'),
    ('DL1252-04', 'D. L. N.° 1252 - Invierte.pe (TUO D.S. 242-2018-EF)', 'DL_1252', '2018-TUO', 'Cierre de brechas de infraestructura (Arts. 1 y 3.a)',
     'Art. 1.- Objeto: Créase el Sistema Nacional de Programación Multianual y Gestión de Inversiones con la finalidad de orientar el uso de los recursos públicos destinados a la inversión para la efectiva prestación de servicios y la provisión de la infraestructura necesaria para el desarrollo del país. Art. 3.a) La programación multianual de la inversión debe ser realizada considerando como principal objetivo el cierre de brechas de infraestructura o de acceso a servicios públicos para la población. Art. 3.d) Los recursos destinados a la inversión deben procurar el mayor impacto en la sociedad. Fuente: leyes.congreso.gob.pe/Documentos/DecretosLegislativos/01252.pdf', TRUE, FALSE, 'public'),
    ('DL1252-05', 'D. L. N.° 1252 - Invierte.pe (TUO D.S. 242-2018-EF)', 'DL_1252', '2018-TUO', 'Funcionamiento y seguimiento (Arts. 4.1.d, 5.2 y 8)',
     'Art. 4.1.d) Funcionamiento: Comprende la operación y mantenimiento de los activos generados con la ejecución de la inversión pública y la provisión de los servicios implementados con dicha inversión. En esta fase las inversiones pueden ser objeto de evaluaciones ex post con el fin de obtener lecciones aprendidas que permitan mejoras en futuras inversiones, así como la rendición de cuentas. Art. 5.2.- El MEF gestiona los mecanismos para el seguimiento y monitoreo a través del Sistema de Seguimiento de Inversiones y el Banco de Inversiones. Art. 8.- Proceso de Seguimiento y Evaluación de las inversiones. Fuente: busquedas.elperuano.pe - D.S. 242-2018-EF', TRUE, FALSE, 'public'),
    ('DL1252-06', 'D. L. N.° 1252 - Invierte.pe (TUO D.S. 242-2018-EF)', 'DL_1252', '2018-TUO', 'Órganos del sistema Invierte.pe: OPMI, UF, UEI (Art. 5)',
     'Art. 5.1.- Son órganos del Sistema: la DGPMI del MEF, los Órganos Resolutivos, las OPMI, las Unidades Formuladoras y las Unidades Ejecutoras de Inversiones. Art. 5.4.- Las OPMI son responsables de la fase de Programación Multianual, verifican el enmarcamiento de la inversión, y realizan el seguimiento de metas e indicadores. Art. 5.5.- Las UF son responsables de la fase de Formulación y Evaluación; aplican metodologías, parámetros y normas técnicas; elaboran fichas técnicas y estudios de preinversión; y declaran la viabilidad. Art. 5.7.- Las UEI son responsables de la ejecución y se sujetan al diseño aprobado en el Banco de Inversiones. Fuente: leyes.congreso.gob.pe/Documentos/DecretosLegislativos/01252.pdf', TRUE, FALSE, 'public'),

    ('LEY32069-01', 'Ley N.° 32069 - Ley General de Contrataciones Públicas', 'LEY_32069', '2024-v1', 'Principios de contratación pública (Art. 5)',
     'Art. 5.1.- Las contrataciones públicas se rigen bajo los siguientes principios: c) Valor por dinero: Las entidades contratantes maximizan el valor de lo que obtienen, en términos de eficiencia, eficacia y economía, considerando calidad, sostenibilidad y evaluación de costos y plazos, no procurando únicamente el menor precio. d) Integridad: Conducta obligada de todo participante, guiado por honestidad, veracidad y rendición de cuentas, que evita y denuncia prácticas indebidas o corruptas. i) Transparencia y facilidad de uso: Las actuaciones y decisiones se basan en reglas y criterios claros y accesibles; las entidades garantizan el acceso público y oportuno a la información del proceso. Fuente: El Peruano, 24/06/2024 - spij.minjus.gob.pe', TRUE, FALSE, 'public'),
    ('LEY32069-02', 'Ley N.° 32069 - Ley General de Contrataciones Públicas', 'LEY_32069', '2024-v1', 'Actuaciones preparatorias y requerimiento (Art. 46)',
     'Art. 46.1.- El requerimiento da inicio al proceso de contratación, en el marco de la PMBSO y las etapas presupuestarias, considerando el principio de valor por dinero. El área usuaria determina el requerimiento en coordinación con la dependencia encargada de contrataciones, identificando la finalidad pública y los objetivos de la contratación. Art. 46.2.- Las entidades gestionan las contrataciones considerando todo el ciclo de vida de los bienes, servicios y obras. Art. 46.3.- El requerimiento permite el acceso de los proveedores en condiciones de igualdad, sin obstaculizar la competencia ni direccionar el proceso. Fuente: El Peruano, 24/06/2024 - spij.minjus.gob.pe', TRUE, FALSE, 'public'),
    ('LEY32069-03', 'Ley N.° 32069 - Ley General de Contrataciones Públicas', 'LEY_32069', '2024-v1', 'Métodos de contratación y selección (Arts. 53 y 54)',
     'Art. 54.1.- Son procedimientos de selección competitivos: a) La licitación pública, para bienes y obras. b) El concurso público, para servicios. Art. 54.2.- El reglamento establece modalidades abreviadas y diferenciadas (subasta inversa electrónica, comparación de precios, compra pública de innovación). Art. 54.3.- Las entidades realizan procedimientos de selección competitivos, salvo excepciones previstas en la ley, asegurando que la adjudicación recaiga en la oferta más conveniente bajo el principio de valor por dinero. Art. 34.- Contratos menores ≤ 8 UIT. Fuente: El Peruano, 24/06/2024 - spij.minjus.gob.pe', TRUE, FALSE, 'public'),
    ('LEY32069-04', 'Ley N.° 32069 - Ley General de Contrataciones Públicas', 'LEY_32069', '2024-v1', 'Ejecución contractual y modificaciones (Arts. 63 y 64)',
     'Art. 63.1.- El contrato puede ser modificado por acuerdo entre las partes, por disposición de la entidad o a solicitud del contratista, para alcanzar la finalidad del contrato de manera oportuna y eficiente. Art. 63.2.- Las modificaciones no deben afectar el equilibrio económico-financiero del contrato. Art. 63.3.- Supuestos: a) Prestaciones adicionales, b) Reducción de prestaciones, c) Ampliaciones de plazo, d) Hechos sobrevinientes no imputables a las partes. Art. 64.- Prestaciones adicionales: hasta 25% del contrato original en bienes/servicios; en obras, hasta 15% por la autoridad administrativa y hasta 50% con aprobación del Titular o la Contraloría. Fuente: El Peruano, 24/06/2024 - spij.minjus.gob.pe', TRUE, FALSE, 'public'),
    ('LEY32069-05', 'Ley N.° 32069 - Ley General de Contrataciones Públicas', 'LEY_32069', '2024-v1', 'Solución de controversias y arbitraje (Arts. 76 y 84)',
     'Art. 76.1.- Las controversias sobre ejecución, interpretación, resolución, inexistencia, ineficacia o nulidad del contrato se resuelven mediante: a) Junta de Prevención y Resolución de Disputas (JPRD), b) Conciliación, c) Arbitraje, d) Otros mecanismos de contratos estandarizados internacionales. Art. 84.- El arbitraje es de derecho; puede ser institucional o ad hoc (solo si ≤ 10 UIT). El laudo es definitivo, inapelable y de obligatorio cumplimiento desde su notificación a través de PLADICOP. Los árbitros deben integrar nóminas registradas ante el OECE. Fuente: El Peruano, 24/06/2024 - spij.minjus.gob.pe', TRUE, FALSE, 'public'),
    ('LEY32069-06', 'Ley N.° 32069 - Ley General de Contrataciones Públicas', 'LEY_32069', '2024-v1', 'Transparencia y trazabilidad - PLADICOP (Art. 41)',
     'Art. 41.1.- La Plataforma Digital para las Contrataciones Públicas (PLADICOP) integra los sistemas que garantizan el acceso y disponibilidad de información sobre contrataciones públicas, incluyendo régimen general, regímenes especiales y contratos menores. Art. 41.2.- Las entidades contratantes tienen la obligación de registrar toda la información de las fases de contratación, garantizando transparencia, trazabilidad, acceso público y fiscalización en tiempo real. Art. 41.4.- Los actos publicados en PLADICOP gozan de plena validez jurídica y eficacia, surtiendo efectos de notificación formal. Fuente: El Peruano, 24/06/2024 - spij.minjus.gob.pe', TRUE, FALSE, 'public'),

    ('PDUPDM-01', 'PDM Huancayo 2017-2037 (O.M. N.° 636-2020-MPH/CM)', 'PDU_EL_TAMBO', '2020-OM636', 'Zonificación urbana (Título III del Reglamento de Zonificación)',
     'PDM Huancayo 2017-2037, Título III: Zonificación Urbana y Parámetros Urbanísticos. Clasifica el suelo en zonas: Residencial Densidad Media (RDM) predominante en El Tambo, Residencial Densidad Alta (RDA) sobre ejes viales como Av. Mariscal Castilla, Comercio Zonal (CZ) en corredores como Av. Huancavelica y Calle Real, Industria Elemental (I-1), Equipamiento de Educación (E-1 a E-3 incluyendo UNCP) y Salud (H-1 a H-4 incluyendo Hospital EsSalud), y Zonas de Recreación Pública (ZRP) intangibles para edificación privada. Norma complementaria: D.S. N.° 012-2022-VIVIENDA, Arts. 30 al 42. Fuente: munihuancayo.gob.pe - O.M. N.° 636-2020-MPH/CM', TRUE, FALSE, 'public'),
    ('PDUPDM-02', 'PDM Huancayo 2017-2037 (O.M. N.° 636-2020-MPH/CM)', 'PDU_EL_TAMBO', '2020-OM636', 'Compatibilidad de uso de suelo (Índice de Usos y Cuadro de Compatibilidad)',
     'PDM Huancayo 2017-2037: Si el uso propuesto es catalogado como No Conforme o Incompatible según el Índice de Usos para la zona, la Gerencia de Desarrollo Urbano emite resolución denegatoria obligatoria. Para usos preexistentes no conformes: se prohíben ampliaciones, solo se permiten obras de conservación y seguridad, y en caso de siniestro >50% caduca el derecho. La vía excepcional de cambio de zonificación requiere sustento vial, consulta vecinal de 30 días y aprobación del Concejo por Ordenanza. El ejercicio de uso incompatible sin autorización acarrea clausura definitiva, paralización de obra y multas (RASA). Norma complementaria: Ley N.° 28976, Arts. 7-8 y D.S. N.° 012-2022-VIVIENDA, Arts. 120-124. Fuente: munihuancayo.gob.pe', TRUE, TRUE, 'public'),
    ('PDUPDM-03', 'PDM Huancayo 2017-2037 (O.M. N.° 636-2020-MPH/CM)', 'PDU_EL_TAMBO', '2020-OM636', 'Equipamiento urbano y aportes reglamentarios (RNE TH.010, Arts. 10-14)',
     'PDM Huancayo 2017-2037: En habilitaciones urbanas en El Tambo el titular cede gratuitamente: Recreación Pública (ZRP) 8-13% del área habilitable (frente a vías, pendientes ≤15%), Educación (MINEDU) 2-3%, Parques Zonales 1-2% (MPH) y Otros Fines 1-2% (equipamiento cívico/seguridad). Cuando el aporte resulte menor al área mínima funcional, la normativa autoriza redención en dinero a favor del fondo municipal de equipamiento urbano, calculada sobre el valor arancelario o comercial del predio. Norma complementaria: RNE TH.010, Cap. II, Arts. 10-14 y GH.020, Arts. 18-25. Fuente: munihuancayo.gob.pe - gob.pe/vivienda', TRUE, FALSE, 'public'),
    ('PDUPDM-04', 'PDM Huancayo 2017-2037 (O.M. N.° 636-2020-MPH/CM)', 'PDU_EL_TAMBO', '2020-OM636', 'Zonas de riesgo alto o no mitigable (SINAGERD - Ley 29664)',
     'PDM Huancayo 2017-2037: Las zonas no mitigables son intangibles e inhabitables; se prohíbe la emisión de licencias de edificación, habilitaciones urbanas, constancias de posesión y dotación de redes de servicios definitivos. Sectores críticos en El Tambo: faja marginal del Río Mantaro (riesgo hidrológico), faja marginal del Río Shullcas (desbordes y huaycos), Río Florido y Río Seco (inundaciones pluviales), Canal CIMIRM (desbordes y contaminación), cerros orientales y quebradas (deslizamientos y movimientos en masa). Las terrazas centrales consolidadas poseen mejor capacidad portante y menor riesgo sísmico. Norma complementaria: Ley N.° 29664, Ley N.° 30556 y CENEPRED-SIGRID. Fuente: sigrid.cenepred.gob.pe - munieltambo.gob.pe', TRUE, TRUE, 'public'),
    ('PDUPDM-05', 'PDM Huancayo 2017-2037 (O.M. N.° 636-2020-MPH/CM)', 'PDU_EL_TAMBO', '2020-OM636', 'Sistema vial y movilidad urbana (Reglamento del Sistema Vial Metropolitano)',
     'PDM Huancayo 2017-2037, Reglamento del Sistema Vial Metropolitano: Clasifica las vías en Expresas (tránsito ininterrumpido con control de accesos, incluyendo Vía de Evitamiento y Autovía del Mantaro), Arteriales (Av. Mariscal Castilla como eje principal, Av. Ferrocarril y Av. Huancavelica), Colectoras (Av. Evitamiento, Av. Mariátegui, Av. Calmell del Solar, Av. Tahuantinsuyo) y Locales (calles residenciales con máx. 30 km/h y veredas mínimo 1.20 m). Toda obra o habilitación nueva debe respetar los retiros de alineamiento vial del Plano de Vías para garantizar el derecho de vía y futuras ampliaciones de calzadas y ciclovías. Norma complementaria: RNE GH.020. Fuente: munihuancayo.gob.pe', TRUE, FALSE, 'public'),
    ('PDUPDM-06', 'PDM Huancayo 2017-2037 (O.M. N.° 636-2020-MPH/CM)', 'PDU_EL_TAMBO', '2020-OM636', 'Desarrollo urbano sostenible y espacio público (Ley DUS 31313)',
     'PDM Huancayo 2017-2037: Los parques, plazas, alamedas y riberas protegidas son bienes de dominio público inalienables, imprescriptibles e inembargables; se prohíbe el cambio de uso de áreas verdes a fines habitacionales o comerciales privados. Ejes ecológicos: recuperación ambiental e intangibilidad de riberas del Shullcas y Mantaro para malecones ecológicos. Huancayo y El Tambo registran un índice de áreas verdes per cápita inferior a 4 m²/hab (frente a 9 m²/hab recomendados por la OMS). El PDM obliga a articular los aportes de recreación y parques zonales para conformar una red conectada de espacios públicos arborizados. Norma complementaria: Ley N.° 31313, D.S. N.° 012-2022-VIVIENDA, Ley N.° 31199 y D.S. N.° 001-2023-VIVIENDA. Fuente: munihuancayo.gob.pe - gob.pe/vivienda', TRUE, FALSE, 'public')
ON CONFLICT (id) DO UPDATE SET
    document_name = EXCLUDED.document_name,
    version = EXCLUDED.version,
    topic = EXCLUDED.topic,
    content = EXCLUDED.content,
    data_origin = EXCLUDED.data_origin;
